name = "test-menu"
main = "index.js" # تأكد أن هذا هو اسم ملف الجافاسكريبت الرئيسي لديك
compatibility_date = "2024-03-01"

# إذا كان مشروعك يحتوي على ملفات HTML/CSS ثابتة (Static Assets)
# قم بإلغاء التعليق عن السطرين التاليين:
# [assets]
# directory = "./"
